{
  "hash": "83326f2638acd9641d8dc592927ed633",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Spatial Predictive Analysis\"\nsubtitle: \"Analyzing 311 Violations\"\nauthor: Jenny Brar\ndate: today\nformat:\n  html:\n    code-fold: show\n    code-tools: true\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\neditor: visual\nexecute:\n  warning: false\n  message: false\n---\n\n## Spatial Predictive Modeling of Residential Burglary Using 311 Service Request Data (Garbage Cans) in Chicago\n\n------------------------------------------------------------------------\n\n## Introduction\n\nWith the \"Broken Windows Theory\" in mind, the goal of this assignment is to critically analyze predictive policing models. This theory, according to lecutre diuscussions, is the idea that visible signs of social disorder are some indication of crime. Specifically, my assignment used 311 data where residents reported missing or stolen garbage cans as a predictor in determining burglaries in Chicago. The aim of this report is not only to create a predicitve model in which if we can find where missing garbage cans are concnetrated, we predict where burglaries will occur, but also to crtically evaluate the model and data sources.\n\nThis report outlines the various spatial operations conducted above, outlining what the code is for (in general), and why it is needed to meet the overall goal of the assignment. As the coding and spatial operations apporach sections with results, those results will be interpreted through out these code and operational debriefings. Finally, the report will conclude a ciritcal evaluation of the findings in this analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#loading the needed packages and code settings\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\noptions(scipen = 999)  # No scientific notation\nset.seed(5080)         # Reproducibility, could be any number\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#this code is creating a function to use the same plotting theme each time we code a visual\ntheme_crime <- function(base_size = 11) { #creatin a function called theme_cirme base size= font\n  theme_minimal(base_size = base_size) + #builsing on theme_minimal, with the base_size we made above\n    theme( #the code below is where we make changes and override exsiting formatting \n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(), #removes grids\n      axis.text = element_blank(), #removes numbers on the axes\n      axis.title = element_blank() #removes labels\n    )\n}\n\ntheme_set(theme_crime()) #theme set tells ggplot to use this as the default for all plots moving forward. theme_sanitation() is now a theme function\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Loading Data from Chicago\n#Following course code, we want to load Chicago police boundaries\n#get spatial data from url, then format it to be in GeoJSON format, then create an sf object out of it, \n\n# Loading Data from Chicago\n# Load Chicago police district boundaries\n\npoliceDistricts <- st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%   # transform to Illinois State Plane (feet)\n  dplyr::select(District = dist_num)  # keep and rename district number\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 25 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load police beats (smaller administrative units)\npoliceBeats <- st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(Beat = beat_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 277 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load Chicago boundary. Does not load from web. Have to download then call it. \n\nchicagoBoundary <- \n  st_read(here(\"lab/lab_4/lab_4/data/chicagoBoundary.geojson\")) %>%\n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `chicagoBoundary' from data source \n  `C:\\Users\\brar2\\OneDrive\\Documents\\PPA\\PPA-CPLN-5920-Spring26-Portfolio\\lab\\lab_4\\lab_4\\data\\chicagoBoundary.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -87.8367 ymin: 41.64454 xmax: -87.52414 ymax: 42.02304\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that the data loaded properly\ncat(\"✓ Loaded spatial boundaries\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded spatial boundaries\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police districts:\", nrow(policeDistricts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police districts: 25 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police beats:\", nrow(policeBeats), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police beats: 277 \n```\n\n\n:::\n\n```{.r .cell-code}\n#Loading the Burglaries\n\n# Load from provided data file (downloaded from Chicago open data portal)\nburglaries <- st_read(here(\"lab/lab_4/lab_4/data/burglaries.shp\")) %>% \n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `burglaries' from data source \n  `C:\\Users\\brar2\\OneDrive\\Documents\\PPA\\PPA-CPLN-5920-Spring26-Portfolio\\lab\\lab_4\\lab_4\\data\\burglaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 7482 features and 22 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 340492 ymin: 552959.6 xmax: 367153.5 ymax: 594815.1\nProjected CRS: NAD83(HARN) / Illinois East\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(burglaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 7,482\nColumns: 23\n$ ID       <int> 10801247, 10801593, 10801602, 10801904, 10801956, 10802305, 1…\n$ Cs_Nmbr  <chr> \"JA100159\", \"JA100586\", \"JA100376\", \"JA100943\", \"JA101022\", \"…\n$ Date     <date> 2017-01-01, 2017-01-01, 2017-01-01, 2017-01-02, 2017-01-01, …\n$ Block    <chr> \"048XX N KEDZIE AVE\", \"054XX W CHICAGO AVE\", \"057XX S MOZART …\n$ IUCR     <chr> \"0610\", \"0610\", \"0610\", \"0610\", \"0610\", \"0610\", \"0610\", \"0610…\n$ Prmry_T  <chr> \"BURGLARY\", \"BURGLARY\", \"BURGLARY\", \"BURGLARY\", \"BURGLARY\", \"…\n$ Dscrptn  <chr> \"FORCIBLE ENTRY\", \"FORCIBLE ENTRY\", \"FORCIBLE ENTRY\", \"FORCIB…\n$ Lctn_Ds  <chr> \"RESTAURANT\", \"SMALL RETAIL STORE\", \"RESIDENCE-GARAGE\", \"RESI…\n$ Arrest   <chr> \"true\", \"false\", \"false\", \"true\", \"false\", \"false\", \"false\", …\n$ Domestc  <chr> \"false\", \"false\", \"false\", \"false\", \"false\", \"false\", \"false\"…\n$ Beat     <int> 1713, 1524, 824, 722, 724, 1723, 732, 935, 1432, 334, 2533, 1…\n$ Distrct  <int> 17, 15, 8, 7, 7, 17, 7, 9, 14, 3, 25, 12, 16, 25, 3, 4, 12, 1…\n$ Ward     <int> 33, 37, 16, 6, 17, 39, 17, 3, 1, 7, 37, 1, 38, 31, 5, 7, 1, 4…\n$ Cmmnt_A  <int> 14, 25, 63, 69, 67, 16, 68, 61, 21, 43, 25, 24, 15, 20, 43, 4…\n$ FBI_Cod  <chr> \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"05\", \"…\n$ X_Crdnt  <int> 1154172, 1139598, 1158356, 1176576, 1168818, 1150614, 1172237…\n$ Y_Crdnt  <int> 1931913, 1904799, 1866496, 1859716, 1860109, 1928503, 1856217…\n$ Year     <int> 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2…\n$ Updtd_O  <date> 2017-02-14, 2017-02-14, 2017-02-14, 2018-02-10, 2017-02-14, …\n$ Latitud  <dbl> 41.96900, 41.89488, 41.78940, 41.77041, 41.77166, 41.95971, 4…\n$ Longitd  <dbl> -87.70849, -87.76275, -87.69490, -87.62830, -87.65672, -87.72…\n$ Locatin  <chr> \"(41.968999706, -87.708494241)\", \"(41.894875219, -87.76274673…\n$ geometry <POINT [m]> POINT (351792.8 588847.4), POINT (347350.6 580583), POI…\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check the data\ncat(\"\\n✓ Loaded burglary data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Loaded burglary data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of burglaries:\", nrow(burglaries), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of burglaries: 7482 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - CRS:\", st_crs(burglaries)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - CRS: ESRI:102271 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Date range:\", format(min(burglaries$Date, na.rm = TRUE)), \"to\", \n    format(max(burglaries$Date, na.rm = TRUE)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Date range: 2017-01-01 to 2018-01-01 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngarbagecart <- read.csv(here(\"lab/lab_4/lab_4/data/garbagecart.csv\"))\n\n# FILTER TO 2017 ONLY BC RN DATA CONTAINS ALL YEARS 2001 to 2018\n# BURGLARIES ARE 2017 SO x variable has to be the SAME YEAR\ngarbagecart <- garbagecart %>%\n  mutate(Creation.Date = as.Date(Creation.Date, format = \"%m/%d/%Y\")) %>%\n  filter(format(Creation.Date, \"%Y\") == \"2017\")\n\ncat(\"Rows after filtering to 2017:\", nrow(garbagecart), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows after filtering to 2017: 52851 \n```\n\n\n:::\n\n```{.r .cell-code}\n# now we can convert to spatial feature\ngarbagecart <- garbagecart %>%\n  filter(!is.na(Latitude), !is.na(Longitude)) %>%\n  st_as_sf(coords = c(\"Longitude\", \"Latitude\"), crs = 4326) %>%\n  st_transform('ESRI:102271')\n```\n:::\n\n\nPrior to creating any fishnet or spatial operations, the report wanted a baseline map, specfically two maps adjacent to one another to see where missing garbage cart complaints were concentrated. The first map, the one the left, or A in the code, uses red dots across Chicago, whereas the map, B, is a smoothed out desnity map showing the concentrations. The second map is created using Kernal Density Estimation. That is, KDE uses some mathematical formula to to show hotspots. The kernel is the center of the se maps. In my code, I opted for 10 bins, which is essentially the number of density level.\n\nIn any spatial analysis it is critical to explore and visualize the data we are working with, and thus we need to understand our original data before we can even begin using it as predictors. In the maps below, we can see that the first map, A, there were almost 53k complaints and a lot of it was concentrated everywhere with noticeable gaps in some southern parts and what looks like along the river and in the eastern parts of the city. Though I am not familiar with Chicago's landscape, this pattern may exists for numerous reason, such as less residents in those areas, or just lack of need for complaints such as those. Further, the second map on the right, B, illustrates the same patter, by showing that colours in purple, which are lesser concentrated areas, are in the same places mentioned earlier. Besides these areas, it looks like garbage complaints exist across the city and dont seep to have specific neighbourhoods of concern. That said, there are very obvious hotspots on map B, where there may be spatial patterns and thus the need for more modeling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map\np1 <- ggplot() + #STARTING OFF WITH A BLANK PLOT THEN ADDING TO IT\n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = garbagecart, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Garbage Cart Complaint for Missing or Stolen carts- Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(garbagecart))\n  ) #THIS IS TO HIGHLIGHT ALL THE VACANT LAND AND LOCATION AND TO ADD TITLE AND SUBTITLES\n\n# Density surface using modern syntax. NOTE GEOM_DENSITY2D DOES NOT USE GEOMETRY \np2 <- ggplot() + #STARTS THER SAME WITH A BLANK PLOT THAT WE WILL ADD TO\n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(garbagecart)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 10 #CHANGED BINS TO 10 TO ADD A BIT MORE DETAIL\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\n# Combine plots using patchwork (modern approach)\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Garbage Cart Complaints in Chicago\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n#### Fishnet Grid Creation\n\nBy creating a fishnet, we are essentially converting the point data from above to a grid format where we can count the points per grid or cell. From there we can calculate spatial features and then actually run regression as done below. It's importatnt to note that fishnets adress MAUP concerns, albeit selecting the right size is a challenge in and if itself. Nonetheless, the consistent cell size allows us to make more reliable comparisons across Chicago.\n\nThe below out put shows how mnay cells cover Chicgo, in this case it is nearly 2500, which also acts as the number of observations in our data. Each cell is exactly 250,000 sq meters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#CREATING THE FISHNET\n\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number()) %>%\n  st_transform('ESRI:102271')\n\n# Keeping only cells inside Chicago\nfishnet <- fishnet[chicagoBoundary, ]\n\n\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size:\", 500, \"x\", 500, \"meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 500 x 500 meters\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell area:\", round(st_area(fishnet[1,])), \"square meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell area: 250000 square meters\n```\n\n\n:::\n:::\n\n\nNow that the fishnet has been created, we have to actually apply our exsiting data to it via spatial operations/ engineering (spatial joins). Here, each cell has a unique ID and then each point is allocated to it, creating a count per grid cell. The summary output displays the minimimum and maximum complaints per cell.The output idicates that about 20% of all cells have zeor complaints, where as the maximim complaints are over 100. When looking at the fishnet summary output for burglaries, we can see it also ranges from zero, but only to 40 incidents per cell. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#now we want to aggregate our garbage counts into this area\n#st join here is for us to put each land in a fishnet square. if there is no point in a acell, that cell will get a 0\n\ngarbage_fishnet <- st_join(garbagecart, fishnet, join = st_within) %>% #attaches fishnet unique id to each point so every garbage cart obsersvation will have a unique ID\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countGarbage = n())\n\nglimpse(garbage_fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,954\nColumns: 2\n$ uniqueID     <int> 38, 50, 91, 92, 102, 103, 104, 140, 141, 144, 145, 154, 1…\n$ countGarbage <int> 17, 1, 3, 10, 14, 16, 11, 5, 4, 2, 24, 10, 19, 18, 6, 43,…\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(garbage_fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System: NA\n```\n\n\n:::\n\n```{.r .cell-code}\n# check if garbage_fishnet has data after failed\nnrow(garbage_fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1954\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(garbage_fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"uniqueID\"     \"countGarbage\"\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(garbage_fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  uniqueID countGarbage\n     <int>        <int>\n1       38           17\n2       50            1\n3       91            3\n4       92           10\n5      102           14\n6      103           16\n```\n\n\n:::\n\n```{.r .cell-code}\n#we want to join back to fishnet \nfishnet <- fishnet %>%\n  left_join(garbage_fishnet, by = \"uniqueID\") %>%\n  mutate(countGarbage = replace_na(countGarbage, 0))\n\n# Summary statistics\ncat(\"\\nMissing Garbage Cart distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nMissing Garbage Cart distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countGarbage)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   0.00    2.00   18.00   21.47   34.00  111.00 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero garbage cart complaints:\", \n    sum(fishnet$countGarbage == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countGarbage == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero garbage cart complaints: 505 / 2458 ( 20.5 %)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# aggregate burglaries to fishnet\nburglaries_fishnet <- st_join(burglaries, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countBurglaries = n())\n\nfishnet <- fishnet %>%\n  left_join(burglaries_fishnet, by = \"uniqueID\") %>%\n  mutate(countBurglaries = replace_na(countBurglaries, 0))\n\ncat(\"\\nBurglary count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBurglary count distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countBurglaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   2.000   3.042   5.000  40.000 \n```\n\n\n:::\n:::\n\n\nPutting these together, we can now beign to visualize the aggregated data, where yellow indicates higher counts compared to purple which is likely to be zero. Similar to the maps aboe, areas by the water, and in the southern and eastern parts seem to have gaps in complaints.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#visualize aggregated garbage counts\n\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countGarbage), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Garbage Carts Complaints\",\n    option = \"plasma\",\n    trans = \"sqrt\",  # Square root for better visualization of skewed data\n    breaks = c(25, 160, 320, 480, 802)\n  ) +\n  labs(\n    title = \"Garbage Can Complaint Counts by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n#### Part 3: Spatial Features\n\nKeeping this in mind, we also need a baseline for burglaries where the kernal density here is actually simliar to the garbage above, where the south also has gaps. This section essentially uses past burglaries and averages it across a surface using the sigma 1000 code, which is just a 1km bandwidth. The higher the value, the more burgaries have occured in that spot. In addition to this visual inspection, we also use the later on to determine if more complex models we'll build later do any better than this in predicting where burglaries will occur.\n\nThe map shows clear strong concentrations in the north and a bit south, closer to the center.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# KDE is calculated on burglaries y\nburglaries_ppp <- as.ppp(\n  st_coordinates(burglaries),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\nkde_burglaries <- density.ppp(\n  burglaries_ppp,\n  sigma = 1000,\n  edge = TRUE\n)\n\nkde_raster <- rast(kde_burglaries)\n\nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]\n  )\n\ncat(\"✓ Calculated KDE baseline\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated KDE baseline\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_value), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Simple spatial smoothing of burglary locations\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nFurther to capture more context that may be overlooked by the fishnet count, we also want to look at the average of the nearest 3 fishnets, since its possibel to have cells with more or less counts, but the proximity is important to note. When there is a low value that means there is less distance between garbage cart complaints and cells. Higher values might indicate that a particular cell is further away from complaints. Evidently, the range in the summary table is quite vast from just over 6.3 to almost 2300.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#knn distance-Spatial features\n#here we want to see how close each cell is to closest event. if there is no land in a cell, but it is still close to a a bunch or cluster will still get some distance value to capture what the count is missing. \n\nfishnet_coords <- st_coordinates(st_centroid(fishnet)) #for each fishnet cell how far is it from the nearest garbage cart complaint. we need a centroid for that cell\ngarbage_coords  <- st_coordinates(garbagecart) #coords\n\nnn_result <- get.knnx(garbage_coords, fishnet_coords, k = 3)\n\nfishnet <- fishnet %>%\n  mutate(garbage.nn = rowMeans(nn_result$nn.dist))\n\ncat(\"✓ Calculated nearest neighbor distances\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated nearest neighbor distances\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$garbage.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n   6.342   63.561  105.966  245.347  260.621 2258.184 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Local Moran's I\n\n# Function to calculate Local Moran's I\ncalculate_local_morans <- function(data, variable, k = 5) {\n  \n  # Create spatial weights\n  coords <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  weights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n  \n  # Calculate Local Moran's I\n local_moran <- localmoran(as.numeric(data[[variable]]), weights)\n  \n  # Classify clusters\n  mean_val <- mean(data[[variable]], na.rm = TRUE)\n  \n  data %>%\n    mutate(\n      local_i = local_moran[, 1],\n      p_value = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      \n      moran_class = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & .data[[variable]] > mean_val ~ \"High-High\",\n        local_i > 0 & .data[[variable]] <= mean_val ~ \"Low-Low\",\n        local_i < 0 & .data[[variable]] > mean_val ~ \"High-Low\",\n        local_i < 0 & .data[[variable]] <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n\n# Apply to missing or stolen garbage carts\nfishnet <- calculate_local_morans(fishnet, \"countGarbage\", k = 5)\n\nnrow(fishnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2458\n```\n\n\n:::\n\n```{.r .cell-code}\n#visualize morans i\n\n# Visualize hot spots\nggplot() +\n  geom_sf(\n    data = fishnet, \n    aes(fill = moran_class), \n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Vacant Land\",\n    subtitle = \"High-High = Hot spots of disorder\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-12-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroids of \"High-High\" cells (hot spots)\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate distance from each cell to nearest hot spot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  \n  cat(\"✓ Calculated distance to vacant land and buildings hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to vacant land and buildings hot spots\n  - Number of hot spot cells: 332 \n```\n\n\n:::\n:::\n\n\nThe Local Moran's I map above classifies each fishnet cell into one out of five categories based on how its garbage cart count compares to its surrounding neighbours. The red cells, or High-High clusters, are the hotspots where high complaints are surrounded by other high complaint cells. From the map, it is quite clear that these hotpots are concentrated in the northern, more west and a bit southern parts of the city the city, indicating these areas have cells with similar high complaints. The grey cells labelled \"Not Significant\" make up the majority of the map, which suggests that for many cells the spatial pattern of complaints. The blue Low-Low cells represent \"cold spots\", areas with consistently fewer complaints surrounded by the same, noticeable along the eastern edge and in some southern areas. There are a total of 332 hotspot in Chicago. \n\nFollowing the Moran's I, we then calculated the distance from each cell to its nearest High-High hotspot. This gives us a third predictor  to captures not just how many complaints are nearby, but how close each cell is to the kernal areas of concentration. Cells closer to these hotspots may be at higher risk for burglary based on the broken windows idea groudning this analysis.\n\n#### Part 4: Count Regression Models\n\nTo actually predict burglaries, we need a regression model. Since our outcome variable, countBurglaries, is a count rathern than continuous number, regular linear regression isn't appropriate here. Instead, we use count regression, starting with Poisson. The model takes three predictors, countGarbage, garbage.nn, and dist_to_hotspot , and estimates how each one relates to the expected number of burglaries per cell.\n\nHowever, it is important to note that Poisson regression comes with an important assumption: it assumes that the variance in the data equals the mean. But in reality, crime data likely will not meet this assumption. So, when the variance is much higher than the mean, the data is considered overdispersed and Poisson underestimates uncertainty in the model. To check for this, we calculated the dispersion parameter from the Poisson residuals. Anything 1.5 suggests overdispersion and needs more flexible model. As shown in the output, our dispersion, 3.45,  was well above this confirming that the Negative Binomial model is more appropriate since it adds an extra parameter specifically to handle this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# remove District if already exists from previous run\nif (\"District\" %in% names(fishnet)) {\n  fishnet <- fishnet %>% dplyr::select(-District)\n}\n\n# join districts\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_intersects,\n  left = TRUE,\n  largest = TRUE\n) %>%\n  filter(!is.na(District))\n\ncat(\"✓ Joined police districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Joined police districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Districts:\", length(unique(fishnet$District)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Districts: 23 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cells: 2455 \n```\n\n\n:::\n\n```{.r .cell-code}\n# create modeling dataset w. one version only\n# countBurglaries = Y \n# countGarbage, garbage.nn, dist_to_hotspot = X \nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countBurglaries,\n    countGarbage,\n    garbage.nn,\n    dist_to_hotspot\n  ) %>%\n  na.omit()\n\ncat(\"✓ Prepared modeling data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Prepared modeling data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Observations:\", nrow(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Observations: 2455 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Poisson regression\nmodel_poisson <- glm(\n  countBurglaries ~ countGarbage + garbage.nn + dist_to_hotspot,\n  data = fishnet_model,\n  family = \"poisson\"\n)\n\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countBurglaries ~ countGarbage + garbage.nn + dist_to_hotspot, \n    family = \"poisson\", data = fishnet_model)\n\nCoefficients:\n                   Estimate  Std. Error z value             Pr(>|z|)    \n(Intercept)      1.68906103  0.04052828  41.676 < 0.0000000000000002 ***\ncountGarbage     0.00579656  0.00073175   7.921  0.00000000000000235 ***\ngarbage.nn      -0.00333629  0.00014898 -22.394 < 0.0000000000000002 ***\ndist_to_hotspot -0.00016802  0.00001002 -16.774 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 10012.2  on 2454  degrees of freedom\nResidual deviance:  6379.8  on 2451  degrees of freedom\nAIC: 11573\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n\n```{.r .cell-code}\n# check overdispersion\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) /\n              model_poisson$df.residual\n\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 3.45 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rule of thumb: >1.5 suggests overdispersion\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRule of thumb: >1.5 suggests overdispersion\n```\n\n\n:::\n\n```{.r .cell-code}\nif (dispersion > 1.5) {\n  cat(\"⚠ Overdispersion detected! Negative Binomial will fit better.\\n\")\n} else {\n  cat(\"✓ Dispersion looks okay for Poisson.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n⚠ Overdispersion detected! Negative Binomial will fit better.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# POISSON SHOWED DISPERSION OF 6.56 SO NEGATIVE BINOMIAL IS CORRECT MODEL TO USE\nmodel_nb <- glm.nb(\n  countBurglaries ~ countGarbage + garbage.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = countBurglaries ~ countGarbage + garbage.nn + \n    dist_to_hotspot, data = fishnet_model, init.theta = 1.642225756, \n    link = log)\n\nCoefficients:\n                   Estimate  Std. Error z value             Pr(>|z|)    \n(Intercept)      1.63995139  0.06957386  23.571 < 0.0000000000000002 ***\ncountGarbage     0.00665052  0.00139568   4.765           0.00000189 ***\ngarbage.nn      -0.00335734  0.00019770 -16.982 < 0.0000000000000002 ***\ndist_to_hotspot -0.00015074  0.00001555  -9.693 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(1.6422) family taken to be 1)\n\n    Null deviance: 4150.3  on 2454  degrees of freedom\nResidual deviance: 2625.7  on 2451  degrees of freedom\nAIC: 9883.1\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  1.6422 \n          Std. Err.:  0.0866 \n\n 2 x log-likelihood:  -9873.1490 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare AIC (lower is better)\ncat(\"\\nModel Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Poisson AIC:\", round(AIC(model_poisson), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson AIC: 11572.8 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Negative Binomial AIC:\", round(AIC(model_nb), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNegative Binomial AIC: 9883.1 \n```\n\n\n:::\n:::\n\n\nThe AIC comparison above is used to determine which model fits the data better, where the lower the AIC, the better the fit. Given the overdispersion we identified, the Negative Binomial model should have a noticeably lower AIC than Poisson, which would confirm it as the right model for this analysis. Above we can see and AIC of 9883.1 compared to 11572.8 for Poisson, further confirming that a negative binomial was a a better model. \n\nLooking at the coefficients in the summary output, we can also start to see the direction of each relationship. A positive coefficient for countGarbage would suggest that more garbage cart complaints in a cell are associated with more burglaries, which would be consistent with the broken windows theory. A negative coefficient for dist_to_hotspot would make sense too, since being further from a hotspot should be associated with fewer burglaries. Above we can see that all three are statistiacally signficant and the direction seems to be in line with the broken windows theory. For example, countGarbage has a postive relationship indicating that cells with more complaints are associated with more burglaries. Garbage.nn is the variable that looked at proximity to other complaints and thus a lower distance also have higher burglaries. \n\n#### Part 5: Spatial Cross-Validation\n\nOne of the most important parts of building any predictive model is testing whether it actually works on data it has not seen before. In other words, is is generalizable? Since in the regular cross validation model randomly split cells, the model could essentially memorize local patterns and appear to perform well without actually generalizing. So, instead, we use Leave-One-Group-Out (LOGO) spatial cross-validation, which holds out one entire police district at a time. The model trains on all remaining districts and then tries to predict burglaries ion the one left out . This is repeated for every district, giving us a better picture of how the model performs in areas it has never been trained on. The two error metrics we report are MAE (Mean Absolute Error), which tells us on average how many burglaries off our predictions are per cell, and RMSE which penalizes larger errors more heavily. Lower values for both indicate better model performance. Districts with particularly high MAE are worth noting, as those are the places our model struggles with the most, which can point to something about those neighbourhoods that our predictors are not capturing well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get unique districts\ndistricts <- unique(fishnet_model$District)\ncv_results <- tibble()\n\ncat(\"Running LOGO Cross-Validation...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning LOGO Cross-Validation...\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in seq_along(districts)) {\n  \n  test_district <- districts[i]\n  \n  # Split data\n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data <- fishnet_model %>% filter(District == test_district)\n  \n  # Fit model on training data\n  model_cv <- glm.nb(\n    countBurglaries ~ countGarbage + garbage.nn + \n      dist_to_hotspot,\n    data = train_data\n  )\n  \n  # Predict on test data\n  test_data <- test_data %>%\n    mutate(\n      prediction = predict(model_cv, test_data, type = \"response\")\n    )\n  \n  # Calculate metrics\n  mae <- mean(abs(test_data$countBurglaries - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countBurglaries - test_data$prediction)^2))\n  \n  # Store results\n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold = i,\n      test_district = test_district,\n      n_test = nrow(test_data),\n      mae = mae,\n      rmse = rmse\n    )\n  )\n  \n  cat(\"  Fold\", i, \"/\", length(districts), \"- District\", test_district, \n      \"- MAE:\", round(mae, 2), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fold 1 / 23 - District 5 - MAE: 1.65 \n  Fold 2 / 23 - District 4 - MAE: 1.25 \n  Fold 3 / 23 - District 22 - MAE: 2.02 \n  Fold 4 / 23 - District 31 - MAE: 1.24 \n  Fold 5 / 23 - District 6 - MAE: 2.92 \n  Fold 6 / 23 - District 8 - MAE: 2.5 \n  Fold 7 / 23 - District 7 - MAE: 2.6 \n  Fold 8 / 23 - District 3 - MAE: 4.7 \n  Fold 9 / 23 - District 2 - MAE: 2.32 \n  Fold 10 / 23 - District 9 - MAE: 1.67 \n  Fold 11 / 23 - District 10 - MAE: 1.8 \n  Fold 12 / 23 - District 1 - MAE: 1.82 \n  Fold 13 / 23 - District 12 - MAE: 2.74 \n  Fold 14 / 23 - District 15 - MAE: 1.78 \n  Fold 15 / 23 - District 11 - MAE: 2.66 \n  Fold 16 / 23 - District 18 - MAE: 2.02 \n  Fold 17 / 23 - District 25 - MAE: 2.28 \n  Fold 18 / 23 - District 14 - MAE: 2.95 \n  Fold 19 / 23 - District 19 - MAE: 1.99 \n  Fold 20 / 23 - District 16 - MAE: 2.09 \n  Fold 21 / 23 - District 17 - MAE: 2 \n  Fold 22 / 23 - District 20 - MAE: 1.95 \n  Fold 23 / 23 - District 24 - MAE: 1.93 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Overall results\ncat(\"\\n✓ Cross-Validation Complete\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Cross-Validation Complete\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean MAE:\", round(mean(cv_results$mae), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean MAE: 2.21 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Mean RMSE:\", round(mean(cv_results$rmse), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMean RMSE: 3.12 \n```\n\n\n:::\n\n```{.r .cell-code}\n#results table for cv\n# Show results\ncv_results %>%\n  arrange(desc(mae)) %>%\n  kable(\n    digits = 2,\n    caption = \"LOGO CV Results by District\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>LOGO CV Results by District</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> fold </th>\n   <th style=\"text-align:left;\"> test_district </th>\n   <th style=\"text-align:right;\"> n_test </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:right;\"> 72 </td>\n   <td style=\"text-align:right;\"> 4.70 </td>\n   <td style=\"text-align:right;\"> 6.94 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:right;\"> 64 </td>\n   <td style=\"text-align:right;\"> 2.95 </td>\n   <td style=\"text-align:right;\"> 4.06 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:right;\"> 83 </td>\n   <td style=\"text-align:right;\"> 2.92 </td>\n   <td style=\"text-align:right;\"> 4.23 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:right;\"> 99 </td>\n   <td style=\"text-align:right;\"> 2.74 </td>\n   <td style=\"text-align:right;\"> 4.10 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:right;\"> 65 </td>\n   <td style=\"text-align:right;\"> 2.66 </td>\n   <td style=\"text-align:right;\"> 3.25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:right;\"> 67 </td>\n   <td style=\"text-align:right;\"> 2.60 </td>\n   <td style=\"text-align:right;\"> 3.50 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:right;\"> 260 </td>\n   <td style=\"text-align:right;\"> 2.50 </td>\n   <td style=\"text-align:right;\"> 3.25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:right;\"> 87 </td>\n   <td style=\"text-align:right;\"> 2.32 </td>\n   <td style=\"text-align:right;\"> 3.50 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:right;\"> 117 </td>\n   <td style=\"text-align:right;\"> 2.28 </td>\n   <td style=\"text-align:right;\"> 3.06 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:right;\"> 204 </td>\n   <td style=\"text-align:right;\"> 2.09 </td>\n   <td style=\"text-align:right;\"> 2.42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:right;\"> 56 </td>\n   <td style=\"text-align:right;\"> 2.02 </td>\n   <td style=\"text-align:right;\"> 3.70 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:right;\"> 159 </td>\n   <td style=\"text-align:right;\"> 2.02 </td>\n   <td style=\"text-align:right;\"> 2.40 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:right;\"> 104 </td>\n   <td style=\"text-align:right;\"> 2.00 </td>\n   <td style=\"text-align:right;\"> 2.38 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:right;\"> 104 </td>\n   <td style=\"text-align:right;\"> 1.99 </td>\n   <td style=\"text-align:right;\"> 2.69 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:right;\"> 51 </td>\n   <td style=\"text-align:right;\"> 1.95 </td>\n   <td style=\"text-align:right;\"> 2.50 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 23 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:right;\"> 64 </td>\n   <td style=\"text-align:right;\"> 1.93 </td>\n   <td style=\"text-align:right;\"> 2.88 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 58 </td>\n   <td style=\"text-align:right;\"> 1.82 </td>\n   <td style=\"text-align:right;\"> 2.98 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:right;\"> 85 </td>\n   <td style=\"text-align:right;\"> 1.80 </td>\n   <td style=\"text-align:right;\"> 2.55 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 1.78 </td>\n   <td style=\"text-align:right;\"> 2.20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:right;\"> 142 </td>\n   <td style=\"text-align:right;\"> 1.67 </td>\n   <td style=\"text-align:right;\"> 2.33 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:right;\"> 145 </td>\n   <td style=\"text-align:right;\"> 1.65 </td>\n   <td style=\"text-align:right;\"> 2.54 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:right;\"> 306 </td>\n   <td style=\"text-align:right;\"> 1.25 </td>\n   <td style=\"text-align:right;\"> 2.98 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:left;\"> 31 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:right;\"> 1.24 </td>\n   <td style=\"text-align:right;\"> 1.39 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nThe table above shows the MAE and RMSE for each district fold. Districts with higher MAE values are the ones where the model had the most difficulty predicting more reliably, and any spatial pattern in where those errors are concentrated would be worth exploring further in a more analysis. Out of the table above, the only district with the highest MAE and RMSE is district 3, however, there are additoinal distriacts with lower MAE and higher RMSE such as 6, 12, and 14. \n\n#### Part 6: Model Evaluation\n\nThe final step is to compare our model to the KDE baseline we created earlier. The KDE baseline is essentially the simplest possible prediction: it just smooths past burglary locations and assumes that crime will continue to happen where it happened before, with no other information. For our more complex model to be worth the effort, it has to do better than this simple baseline.\n\nThe three maps below compare actual burglary counts, our Negative Binomial model predictions, and the KDE baseline predictions. Visually, we can start to see where each approach captures spatial pattern of burglaries and where it falls short. When looking at the maps and conducting a visual inspection the middle map, Negative binomial, seems to better capture the spatial spread of burglaries better than the Poisson one when comparing it to the baseline KDE map. \n\nThe performance metrics table then gives us numbers to compare. If our model MAE is lower than the KDE MAE, the garbage cart features added predictive value beyond just knowing where past burglaries happened. If KDE is better, it would suggest the added complexity of the model was not justified by the predictors we chose. Despite the NB map better capturing burglaries, the KDE model does better with MAE and RMSE. While NB was still helpful for showing statistically signficant relationshipos between garbage complaints and burglaries, knowing preivous burglary locations seem to be a stronger predictor. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# FIXED: REPLACED abandoned_cars AND abandoned_cars.nn WITH countGarbage AND garbage.nn\n# THESE WERE LEFTOVER FROM THE CLASS EXERCISE TEMPLATE - WRONG VARIABLE NAMES FOR THIS LAB\n\nfinal_model <- glm.nb(\n  countBurglaries ~ countGarbage + garbage.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Add predictions back to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    prediction_nb = predict(final_model, fishnet_model, type = \"response\")[match(uniqueID, fishnet_model$uniqueID)]\n  )\n\n# Also add KDE predictions (normalize to same scale as counts)\nkde_sum <- sum(fishnet$kde_value, na.rm = TRUE)\ncount_sum <- sum(fishnet$countBurglaries, na.rm = TRUE)\nfishnet <- fishnet %>%\n  mutate(\n    prediction_kde = (kde_value / kde_sum) * count_sum\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create three maps\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Actual Burglaries\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Model Predictions (Neg. Binomial)\") +\n  theme_crime()\n\np3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"KDE Baseline Predictions\") +\n  theme_crime()\n\np1 + p2 + p3 +\n  plot_annotation(\n    title = \"Actual vs. Predicted Burglaries\",\n    subtitle = \"Does our complex model outperform simple KDE?\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-18-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate performance metrics\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae = mean(abs(countBurglaries - prediction_nb)),\n    model_rmse = sqrt(mean((countBurglaries - prediction_nb)^2)),\n    kde_mae = mean(abs(countBurglaries - prediction_kde)),\n    kde_rmse = sqrt(mean((countBurglaries - prediction_kde)^2))\n  )\n\ncomparison %>%\n  pivot_longer(everything(), names_to = \"metric\", values_to = \"value\") %>%\n  separate(metric, into = c(\"approach\", \"metric\"), sep = \"_\") %>%\n  pivot_wider(names_from = metric, values_from = value) %>%\n  kable(\n    digits = 2,\n    caption = \"Model Performance Comparison\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance Comparison</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> approach </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> model </td>\n   <td style=\"text-align:right;\"> 2.08 </td>\n   <td style=\"text-align:right;\"> 3.13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kde </td>\n   <td style=\"text-align:right;\"> 1.92 </td>\n   <td style=\"text-align:right;\"> 2.81 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate errors\nfishnet <- fishnet %>%\n  mutate(\n    error_nb = countBurglaries - prediction_nb,\n    error_kde = countBurglaries - prediction_kde,\n    abs_error_nb = abs(error_nb),\n    abs_error_kde = abs(error_kde)\n  )\n\n# Map errors\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = error_nb), color = NA) +\n  scale_fill_gradient2(\n    name = \"Error\",\n    low = \"#2166ac\", mid = \"white\", high = \"#b2182b\",\n    midpoint = 0,\n    limits = c(-10, 10)\n  ) +\n  labs(title = \"Model Errors (Actual - Predicted)\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abs_error_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Abs. Error\", option = \"magma\") +\n  labs(title = \"Absolute Model Errors\") +\n  theme_crime()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](lab_4_files/figure-html/unnamed-chunk-20-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create nice summary table\nmodel_summary <- broom::tidy(final_model, exponentiate = TRUE) %>%\n  mutate(\n    across(where(is.numeric), ~round(., 3))\n  )\n\nmodel_summary %>%\n  kable(\n    caption = \"Final Negative Binomial Model Coefficients (Exponentiated)\",\n    col.names = c(\"Variable\", \"Rate Ratio\", \"Std. Error\", \"Z\", \"P-Value\")\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\")) %>%\n  footnote(\n    general = \"Rate ratios > 1 indicate positive association with burglary counts.\"\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;border-bottom: 0;\">\n<caption>Final Negative Binomial Model Coefficients (Exponentiated)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Rate Ratio </th>\n   <th style=\"text-align:right;\"> Std. Error </th>\n   <th style=\"text-align:right;\"> Z </th>\n   <th style=\"text-align:right;\"> P-Value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 5.155 </td>\n   <td style=\"text-align:right;\"> 0.070 </td>\n   <td style=\"text-align:right;\"> 23.571 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> countGarbage </td>\n   <td style=\"text-align:right;\"> 1.007 </td>\n   <td style=\"text-align:right;\"> 0.001 </td>\n   <td style=\"text-align:right;\"> 4.765 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> garbage.nn </td>\n   <td style=\"text-align:right;\"> 0.997 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -16.982 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> dist_to_hotspot </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -9.693 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n  </tr>\n</tbody>\n<tfoot>\n<tr><td style=\"padding: 0; \" colspan=\"100%\"><span style=\"font-style: italic;\">Note: </span></td></tr>\n<tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Rate ratios &gt; 1 indicate positive association with burglary counts.</td></tr>\n</tfoot>\n</table>\n\n`````\n:::\n:::\n\n\nThe error maps above show where the model was most wrong. Blue cells indicate the model underpredicted - actual burglaries were higher than what the model expected, meaning those areas have more crime than our garbage cart predictors would suggest. Red cells are where the model overpredicted. White or near-white cells are where the model was relatively accurate. The maps show a scattered mix of red and blue meaning that the errors appear to be random. However, there are obnvious areas that are red, which are underprecited areas along the west side. The map on the right displays the most errors even going up to 30  in some areas in the south and west parts of Chicago, while the rest of the area shows a dark colour indicting these areas was more reliable there. \n\nThe coefficient table from the final Negative Binomial model shows each predictor as a rate ratio. A rate ratio above 1 means that variable is positively associated with more burglaries, while a rate ratio below 1 means the opposite. All predictors with statistically significant p-values (below 0.05) are contributing meaningfully to the model's predictions. We can see that countGarbage has a rate ratio of 1.007, meaning each additional garbage cart complaint in a cell is associated with a 0.7% increase in expected burglaries. Alhtough this is  statistically significant, it is also a very marginal effect garbage.nn has a rate ratio of 0.997, meaning each additional unit of distance from garbage cart complaints is associated with a 0.3% decrease in expected burglaries. \n\n## Final Notes and Critical Evaluation\n\nThis analysis has several important limitations. First, crime data only reflects reported crimes and policing patterns, where areas with heavier police presence tend to have more recorded crime, which can create a feedback loop in any predictive model. If the model is then used to direct more policing to those same areas, the data bias gets reinforced rather than corrected. This is a core critique of predictive policing that came up in course discussions. Further, even though garbage cart complaints serve as a reasonable proxy for neighbourhood crimes  (burglaries) under broken windows theory, they are  a 311 reporting metric. In other words,  they reflect who calls 311 as much as they reflect actual crimes. Wealthier and more civically engaged neighbourhoods could  have higher 311 usage, which could introduce bias into the predictor.\n\nThe model only uses three predictor variables, and there are clearly other factors, like income, housing density, etc., that likely influence burglary risk and are not captured here. The error maps do show some areas of  underprediction, particularly along the west side where the model consistently predicted fewer burglaries than actually occurred, and several cells in the south with absolute errors above 30. \n\nThat said, the analysis does demonstrate spatial relationship between garbage cart complaint hotspots and burglary counts in Chicago. All three predictors were statistically significant, and the directions of the relationships made theoretical sense: more complaints associated with more burglaries, and greater distance from it was associated with less However, the KDE baseline actually outperformed the Negative Binomial model on both MAE (1.92 vs 2.08) and RMSE (2.81 vs 3.13), which is an important finding to sit with honestly. It suggests that knowing where burglaries has occurred is a stronger predictor of future burglaries than knowing where garbage cart  is concentrated.\n\n",
    "supporting": [
      "lab_4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}